"""7-sheet Excel workbook — rebuild prompt §17. Columns match the spec
exactly (02_Test_Results' 19 columns are quoted verbatim from the spec).
No embedded thumbnails in 04_Evidence_Index — same no-Pillow decision as
Phase 5; evidence is referenced by ID/hash/caption instead, with the
full image available in the portable ZIP package.
"""

import io
import json
from datetime import datetime, timezone

import openpyxl
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE
from openpyxl.utils import get_column_letter

from . import models, hybrid_timing
from .metrics import result_counts, pass_rate, evidence_completeness


def evidence_code(evidence_id: int) -> str:
    return f"EVID-{evidence_id}"


def _clean_cell(value):
    """openpyxl raises IllegalCharacterError and aborts the whole export
    if any cell contains an XML-illegal control character (e.g. a literal
    NUL byte someone pasted into an actual-result field) — strip those
    rather than let one bad field crash every export."""
    if isinstance(value, str):
        return ILLEGAL_CHARACTERS_RE.sub("", value)
    return value


def _append(ws, row):
    ws.append([_clean_cell(v) for v in row])


def _autosize(ws):
    for col_cells in ws.columns:
        length = max((len(str(c.value)) if c.value is not None else 0) for c in col_cells)
        ws.column_dimensions[get_column_letter(col_cells[0].column)].width = min(max(length + 2, 10), 60)


def build_workbook(db, project: models.Project, cycle: models.TestCycle, generated_by: str) -> openpyxl.Workbook:
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    revision = db.query(models.ScriptRevision).filter(models.ScriptRevision.id == cycle.script_revision_id).first()
    suite = db.query(models.TestSuite).filter(models.TestSuite.id == cycle.suite_id).first()

    cases_by_result = {
        r.id: c
        for r, c in (
            db.query(models.CycleTestResult, models.TestCase)
            .join(models.TestCase, models.TestCase.id == models.CycleTestResult.test_case_id)
            .filter(models.CycleTestResult.cycle_id == cycle.id)
            .all()
        )
    }
    results = (
        db.query(models.CycleTestResult)
        .filter(models.CycleTestResult.cycle_id == cycle.id)
        .order_by(models.CycleTestResult.id)
        .all()
    )

    # ---------- 00_Cover ----------
    ws = wb.create_sheet("00_Cover")
    now = datetime.now(timezone.utc)
    for row in [
        ("Application/Project", project.name),
        ("Suite", suite.name if suite else None),
        ("Script Revision", revision.revision_label if revision else None),
        ("Cycle", cycle.name),
        ("Environment", cycle.environment),
        ("Release Version", cycle.release_version),
        ("Target URL", cycle.target_base_url),
        ("Execution Period Start", cycle.started_at),
        ("Execution Period End", cycle.finished_at),
        ("Generated By", generated_by),
        ("Generated Timestamp (UTC)", now.strftime("%Y-%m-%d %H:%M:%S UTC")),
        ("Report Version", "1.0"),
    ]:
        _append(ws, row)
    _autosize(ws)

    # ---------- 01_Execution_Summary ----------
    ws = wb.create_sheet("01_Execution_Summary")
    counts = result_counts(db, cycle.id)
    pr = pass_rate(db, cycle.id)
    ec = evidence_completeness(db, cycle.id)
    _append(ws, ["Status", "Count", "Definition"])
    definitions = {
        "PASS": "Case executed and met its expected result.",
        "FAIL": "Case executed and did not meet its expected result (shown as NG in the UI).",
        "BLOCKED": "Case could not be executed; blocked_reason is required.",
        "NOT_RUN": "Case has not been executed yet.",
        "NOT_APPLICABLE": "Case does not apply this cycle; na_reason required, admin approval required.",
    }
    for status in models.RESULT_STATUSES:
        _append(ws, [status, counts[status], definitions[status]])
    _append(ws, [])
    _append(ws, ["Pass Rate", f"{pr['percent']}%", pr["formula"]])
    _append(ws, ["Evidence Completeness", f"{ec['percent']}%", ec["formula"]])
    _autosize(ws)

    # ---------- 02_Test_Results ----------
    ws = wb.create_sheet("02_Test_Results")
    _append(ws, 
        [
            "Sequence",
            "Test ID",
            "Title",
            "Priority",
            "Traceability",
            "Fixture",
            "Environment",
            "Setup",
            "Action",
            "Validation",
            "Expected Result",
            "Actual Result",
            "Status",
            "Tester",
            "Executed Date",
            "Reviewer",
            "Review Status",
            "Defect ID",
            "Evidence Count",
            "Evidence Reference",
        ]
    )
    for result in results:
        case = cases_by_result.get(result.id)
        if not case:
            continue
        evidence_items = (
            db.query(models.EvidenceItem)
            .filter(models.EvidenceItem.cycle_test_result_id == result.id, models.EvidenceItem.status == "ACTIVE")
            .all()
        )
        _append(ws, 
            [
                case.sequence_no,
                case.checkpoint_code,
                case.title,
                case.priority,
                case.traceability_md,
                case.fixture_md,
                case.environment_md,
                case.setup_md,
                case.action_md,
                case.validation_md,
                case.expected_result_md,
                result.actual_result_md,
                result.status,
                result.executed_by,
                result.executed_at.strftime("%Y-%m-%d %H:%M:%S") if result.executed_at else None,
                result.reviewed_by,
                result.review_status,
                result.defect_reference,
                len(evidence_items),
                ", ".join(evidence_code(e.id) for e in evidence_items),
            ]
        )
    _autosize(ws)

    # ---------- 03_NG_Defects ----------
    ws = wb.create_sheet("03_NG_Defects")
    _append(ws, ["Test ID", "Title", "Severity", "Defect Status", "Actual Result", "Callout Summary", "Evidence Reference"])
    defects_by_result = {}
    for d in db.query(models.Defect).filter(models.Defect.cycle_id == cycle.id).all():
        if d.cycle_test_result_id:
            defects_by_result.setdefault(d.cycle_test_result_id, []).append(d)
    for result in results:
        if result.status != "FAIL":
            continue
        case = cases_by_result.get(result.id)
        if not case:
            continue
        linked_defects = defects_by_result.get(result.id, [])
        evidence_items = (
            db.query(models.EvidenceItem)
            .filter(models.EvidenceItem.cycle_test_result_id == result.id, models.EvidenceItem.status == "ACTIVE")
            .all()
        )
        callout_summary = _callout_summary(db, evidence_items)
        _append(ws, 
            [
                case.checkpoint_code,
                case.title,
                linked_defects[0].severity if linked_defects else "UNSPECIFIED",
                linked_defects[0].status if linked_defects else None,
                result.actual_result_md,
                callout_summary,
                ", ".join(evidence_code(e.id) for e in evidence_items),
            ]
        )
    _autosize(ws)

    # ---------- 04_Evidence_Index ----------
    ws = wb.create_sheet("04_Evidence_Index")
    _append(ws, 
        ["Evidence ID", "Test ID", "Caption", "Captured By", "Captured Date", "Original SHA-256", "Annotation Revision", "Callout Summary", "Package Reference"]
    )
    all_evidence = db.query(models.EvidenceItem).filter(models.EvidenceItem.cycle_id == cycle.id).all()
    for e in all_evidence:
        case = cases_by_result.get(e.cycle_test_result_id)
        callout_summary = _callout_summary(db, [e])
        _append(ws, 
            [
                evidence_code(e.id),
                case.checkpoint_code if case else None,
                e.caption,
                e.captured_by,
                e.captured_at.strftime("%Y-%m-%d %H:%M:%S") if e.captured_at else None,
                e.original_sha256,
                e.current_revision_no,
                callout_summary,
                f"evidence/{case.checkpoint_code if case else 'unknown'}_{evidence_code(e.id)}",
            ]
        )
    _autosize(ws)

    # ---------- 05_Revision_History ----------
    ws = wb.create_sheet("05_Revision_History")
    _append(ws, ["Revision Label", "Status", "Source Filename", "Source SHA-256", "Change Summary", "Published By", "Published At", "Comparison Summary"])
    if suite:
        revisions = (
            db.query(models.ScriptRevision)
            .filter(models.ScriptRevision.suite_id == suite.id)
            .order_by(models.ScriptRevision.revision_number_sort)
            .all()
        )
        for i, rev in enumerate(revisions):
            comparison = "Initial revision" if i == 0 else f"Supersedes revision {revisions[i - 1].revision_label}" if rev.supersedes_revision_id else "—"
            _append(ws, 
                [
                    rev.revision_label,
                    rev.status,
                    rev.source_filename,
                    rev.source_sha256,
                    rev.change_summary,
                    rev.published_by,
                    rev.published_at.strftime("%Y-%m-%d %H:%M:%S") if rev.published_at else None,
                    comparison,
                ]
            )
    _autosize(ws)

    # ---------- 06_Sign_Off ----------
    ws = wb.create_sheet("06_Sign_Off")
    _append(ws, ["Sign-off Type", "Decision", "Actor", "Timestamp", "Comments"])
    for s in db.query(models.SignOff).filter(models.SignOff.cycle_id == cycle.id).order_by(models.SignOff.acted_at).all():
        _append(ws, [s.signoff_type, s.decision, s.actor, s.acted_at.strftime("%Y-%m-%d %H:%M:%S"), s.comment_md])
    _autosize(ws)

    # ---------- HYB-5: hybrid sheets ----------
    # Scoped to this same cycle: every WorkflowRun whose cycle_test_result_id
    # points at a CycleTestResult belonging to this cycle. A standalone
    # workflow run (no cycle_test_result_id) never appears in a per-cycle
    # export -- there is no cycle to attribute it to -- matching the exact
    # scoping the other 7 sheets already use.
    _add_hybrid_sheets(wb, db, cycle)

    return wb


def _add_hybrid_sheets(wb: openpyxl.Workbook, db, cycle: models.TestCycle) -> None:
    result_ids = [r.id for r in db.query(models.CycleTestResult.id).filter(models.CycleTestResult.cycle_id == cycle.id).all()]
    runs = (
        db.query(models.WorkflowRun)
        .filter(models.WorkflowRun.cycle_test_result_id.in_(result_ids) if result_ids else False)
        .order_by(models.WorkflowRun.created_at)
        .all()
    )
    revision_ids = sorted({r.workflow_revision_id for r in runs})
    revisions = db.query(models.WorkflowRevision).filter(models.WorkflowRevision.id.in_(revision_ids)).all() if revision_ids else []
    workflow_ids = sorted({r.workflow_id for r in revisions})
    workflows = db.query(models.WorkflowDefinition).filter(models.WorkflowDefinition.id.in_(workflow_ids)).all() if workflow_ids else []
    workflow_by_id = {w.id: w for w in workflows}
    revision_by_id = {r.id: r for r in revisions}
    steps = (
        db.query(models.WorkflowStep).filter(models.WorkflowStep.revision_id.in_(revision_ids)).order_by(models.WorkflowStep.revision_id, models.WorkflowStep.sequence_no).all()
        if revision_ids
        else []
    )
    run_ids = [r.id for r in runs]

    def _fmt(dt):
        return dt.strftime("%Y-%m-%d %H:%M:%S") if dt else None

    # ---------- Workflow Definitions ----------
    ws = wb.create_sheet("Workflow Definitions")
    _append(ws, ["Workflow ID", "Name", "Description", "Status", "Created By", "Created At"])
    for w in workflows:
        _append(ws, [w.id, w.name, w.description, w.status, w.created_by, _fmt(w.created_at)])
    _autosize(ws)

    # ---------- Workflow Revisions ----------
    ws = wb.create_sheet("Workflow Revisions")
    _append(ws, ["Revision ID", "Workflow ID", "Workflow Name", "Revision Label", "Status", "Published By", "Published At"])
    for r in revisions:
        wf = workflow_by_id.get(r.workflow_id)
        _append(ws, [r.id, r.workflow_id, wf.name if wf else None, r.revision_label, r.status, r.published_by, _fmt(r.published_at)])
    _autosize(ws)

    # ---------- Workflow Steps ----------
    ws = wb.create_sheet("Workflow Steps")
    _append(ws, ["Step ID", "Revision ID", "Sequence", "Step Type", "Description", "Locator Strategy", "Locator Value", "Is Sensitive", "Evidence Policy"])
    for s in steps:
        _append(ws, [s.id, s.revision_id, s.sequence_no, s.step_type, s.description, s.locator_strategy, s.locator_value, s.is_sensitive, s.evidence_policy])
    _autosize(ws)

    # ---------- Workflow Runs ----------
    ws = wb.create_sheet("Workflow Runs")
    _append(
        ws,
        [
            "Run ID", "Workflow Name", "Revision Label", "Status", "Runner ID", "Cycle Test Result ID",
            "Queued By", "Created At", "Started At", "Ended At", "Result Summary",
        ],
    )
    for r in runs:
        rev = revision_by_id.get(r.workflow_revision_id)
        wf = workflow_by_id.get(rev.workflow_id) if rev else None
        _append(
            ws,
            [
                r.id, wf.name if wf else None, rev.revision_label if rev else None, r.status, r.runner_id,
                r.cycle_test_result_id, r.queued_by, _fmt(r.created_at), _fmt(r.started_at), _fmt(r.ended_at), r.result_summary,
            ],
        )
    _autosize(ws)

    # ---------- Step Results ----------
    ws = wb.create_sheet("Step Results")
    _append(
        ws,
        [
            "Step Run ID", "Run ID", "Step ID", "Step Description", "Step Type", "Sequence", "Attempt",
            "Status", "Failure Category", "Locator Used", "Started At", "Ended At", "Duration (s)",
        ],
    )
    step_runs = db.query(models.WorkflowStepRun).filter(models.WorkflowStepRun.workflow_run_id.in_(run_ids)).order_by(models.WorkflowStepRun.workflow_run_id, models.WorkflowStepRun.sequence_no).all() if run_ids else []
    step_by_id = {s.id: s for s in steps}
    for sr in step_runs:
        step = step_by_id.get(sr.workflow_step_id)
        duration = (sr.ended_at - sr.started_at).total_seconds() if sr.started_at and sr.ended_at else None
        _append(
            ws,
            [
                sr.id, sr.workflow_run_id, sr.workflow_step_id, step.description if step else None, step.step_type if step else None,
                sr.sequence_no, sr.attempt_number, sr.status, sr.failure_category, sr.locator_used_json,
                _fmt(sr.started_at), _fmt(sr.ended_at), round(duration, 3) if duration is not None else None,
            ],
        )
    _autosize(ws)

    # ---------- Checkpoint Decisions ----------
    ws = wb.create_sheet("Checkpoint Decisions")
    _append(
        ws,
        [
            "Decision ID", "Run ID", "Step ID", "Decision Revision", "Status", "Actual Result", "Reason",
            "Decided By Email", "Decided At", "Source", "Resume Authorized", "Review Status",
        ],
    )
    decisions = (
        db.query(models.WorkflowCheckpointDecision).filter(models.WorkflowCheckpointDecision.workflow_run_id.in_(run_ids)).order_by(models.WorkflowCheckpointDecision.workflow_run_id, models.WorkflowCheckpointDecision.id).all()
        if run_ids
        else []
    )
    for d in decisions:
        _append(
            ws,
            [
                d.id, d.workflow_run_id, d.workflow_step_id, d.decision_revision_no, d.status, d.actual_result_md, d.reason,
                d.decided_by_email, _fmt(d.decided_at), d.source, d.resume_authorized, d.review_status,
            ],
        )
    _autosize(ws)

    # ---------- Runner Activity ----------
    ws = wb.create_sheet("Runner Activity")
    _append(ws, ["Event ID", "Run ID", "Event Type", "Actor Type", "Created At"])
    events = (
        db.query(models.RunnerExecutionEvent).filter(models.RunnerExecutionEvent.workflow_run_id.in_(run_ids)).order_by(models.RunnerExecutionEvent.workflow_run_id, models.RunnerExecutionEvent.id).all()
        if run_ids
        else []
    )
    for e in events:
        _append(ws, [e.id, e.workflow_run_id, e.event_type, e.actor_type, _fmt(e.created_at)])
    _autosize(ws)

    # ---------- Timing Trends ----------
    ws = wb.create_sheet("Timing Trends")
    _append(
        ws,
        [
            "Run ID", "Queue Delay (s)", "Browser Startup (s)", "Total Run Duration (s)",
            "Execution Duration (s)", "Application Steps Total (s)", "Manual Waiting Total (s)",
        ],
    )
    for r in runs:
        t = hybrid_timing.run_timing(db, r)
        _append(
            ws,
            [
                r.id, t["queue_delay_seconds"], t["browser_startup_seconds"], t["total_run_duration_seconds"],
                t["execution_duration_seconds"], t["total_application_step_seconds"], t["total_manual_waiting_seconds"],
            ],
        )
    _autosize(ws)


def _callout_summary(db, evidence_items: list[models.EvidenceItem]) -> str:
    parts = []
    for e in evidence_items:
        if e.current_revision_no == 0:
            continue
        latest = (
            db.query(models.EvidenceRevision)
            .filter(models.EvidenceRevision.evidence_id == e.id)
            .order_by(models.EvidenceRevision.revision_no.desc())
            .first()
        )
        if not latest:
            continue
        try:
            shapes = json.loads(latest.annotation_json)
        except (TypeError, ValueError):
            continue
        callouts = sum(1 for s in shapes if s.get("type") == "callout")
        if shapes:
            parts.append(f"{evidence_code(e.id)}: {len(shapes)} annotation(s), {callouts} callout(s)")
    return "; ".join(parts)


def workbook_to_bytes(wb: openpyxl.Workbook) -> bytes:
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
